spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/student_?createDatabaseIfNotExist=true
    username: root
    password: avnish
  main:
    allow:
      circular-references: true

server:
  servlet:
    context-path: /student-management